### ISSUE TITLE
请问能共享这篇文章的代码吗

### ISSUE THREAD

**Issue by 22xumeng** [wujunzero/website#4]

**Comment by wujunzero** [comment]
您好，哪一篇？

**Comment by 22xumeng** [comment]
A hybrid ant colony algorithm for the winner determination problem。非常感谢~

从 Windows 版邮件发送

发件人: Wu Jun
发送时间: 2023年2月27日 22:51
收件人: wujunzero/website
抄送: 22xumeng; Author
主题: Re: [wujunzero/website] 请问能共享这篇文章的代码吗 (Issue #4)

您好，哪一篇？

**Comment by wujunzero** [comment]
给我一个联系方式。

**Comment by 22xumeng** [comment]
您好，我的邮箱是2033101@tongji.edu.cn ，谢谢您

**Comment by 22xumeng** [comment]
谢谢~

从 Windows 版邮件发送

发件人: Wu Jun
发送时间: 2023年3月2日 14:42
收件人: wujunzero/website
抄送: 22xumeng; Author
主题: Re: [wujunzero/website] 请问能共享这篇文章的代码吗 (Issue #4)

Closed #4 as completed.
